name: CD

on:
    push:
        tags:
            - "v*"

    workflow_dispatch:

permissions:
    contents: write

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://mango3:mango3@127.0.0.1:5432/trailers_dev

jobs:
    build_api:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: mango3
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_DB: trailers_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package trailers-api --release
            - uses: actions/upload-artifact@v7
              with:
                  name: trailers_api_build
                  path: ./target/release/trailers-api
                  retention-days: 1
                  overwrite: true

    build_cli:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: mango3
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_DB: trailers_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package trailers-cli --release
            - uses: actions/upload-artifact@v7
              with:
                  name: trailers_cli_build
                  path: ./target/release/trailers-cli
                  retention-days: 1
                  overwrite: true

    build_monitor:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_USER: mango3
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_DB: trailers_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package trailers-monitor --release
            - uses: actions/upload-artifact@v7
              with:
                  name: trailers_monitor_build
                  path: ./target/release/trailers-monitor
                  retention-days: 1
                  overwrite: true

    dump_graphql_schema:
        needs: [build_cli]
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: mango3
                    POSTGRES_PASSWORD: mango3
                    POSTGRES_DB: trailers_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v6
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_cli_build
                  path: artifact/
            - run: |
                  chmod +x ./artifact/trailers-cli
                  ./artifact/trailers-cli graphql-schema | tee ./trailers-${{ github.ref_name }}.graphql
            - uses: actions/upload-artifact@v7
              with:
                  name: trailers_graphql_schema
                  path: ./trailers-${{ github.ref_name }}.graphql
                  retention-days: 1
                  overwrite: true

    release:
        needs: [dump_graphql_schema]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_graphql_schema
                  path: artifact/
            - uses: softprops/action-gh-release@v2
              with:
                  files: artifact/trailers-${{ github.ref_name }}.graphql
                  generate_release_notes: true
                  prerelease: ${{ contains(github.ref_name, '-alpha') }}

    deploy:
        needs: [build_api, build_cli, build_monitor]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_api_build
                  path: artifact/
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_cli_build
                  path: artifact/
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_monitor_build
                  path: artifact/
            - name: Run deploy script
              run: ${{ secrets.DEPLOY_SCRIPT }}
